name: Deploy to gh‑pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build‑and‑deploy:
    runs‑on: ubuntu‑latest
    steps:
      - name: Checkout main全部源码
        uses: actions/checkout@v4

      - name: 部署根目录全部文件到 gh‑pages
        uses: peaceiris/actions‑gh‑pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh‑pages
          force_orphan: true
